In [1]:
import numpy as np

获取数组是通过索引(indexing)和切片(slicing)完成    
+ 切片是获取一段特定位置的元素  
+ 索引是获取一个特定位置的元素

### 正规索引
- 切片得到的是原数组的一个视图，修改切片中的内容会改变原数组  
- 索引得到的是原数组的一个复制，修改索引中的内容不会改变原数组

In [3]:
# 一维数组
arr = np.arange(10)
arr[6]

6

In [6]:
a = arr[6]
a = 1000
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = arr[5:8]
b[1] = 12
arr 

array([ 0,  1,  2,  3,  4,  5, 12,  7,  8,  9])

In [11]:
# 二维数组
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [12]:
arr2d[0][2]

3

索引二维数组打了两个中括号好麻烦，索引五维数组不是要打了五个中括号？还有一个简易方法，用`arr2d[0,2]` 也可以索引第一行第三列

In [13]:
arr2d[0,2]

3

切片

In [15]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2d[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [18]:
arr2d[1,:2]

array([4, 5])

In [19]:
arr2d[:2,2]

array([3, 6])

布尔索引  
- 布尔索引，就是用一个由布尔 (boolean) 类型值组成的数组来选择元素的方法。  

In [20]:
code = np.array(['BABA','FB','JD','BABA','JD','FB'])
price = np.array([[170,177,169],[150,159,153],
                  [24,27,26],[165,170,167],
                  [22,23,20],[155,116,157]])
price

array([[170, 177, 169],
       [150, 159, 153],
       [ 24,  27,  26],
       [165, 170, 167],
       [ 22,  23,  20],
       [155, 116, 157]])

In [21]:
code == 'BABA'

array([ True, False, False,  True, False, False])

In [22]:
price[code=='BABA']

array([[170, 177, 169],
       [165, 170, 167]])

In [23]:
price[code=='BABA',1:]

array([[177, 169],
       [170, 167]])

In [26]:
price[(code=='BABA') | (code == 'JD')]

array([[170, 177, 169],
       [ 24,  27,  26],
       [165, 170, 167],
       [ 22,  23,  20]])

In [28]:
# 条件需要小括号
# price[code=='BABA' | code == 'JD']

In [30]:
price[price < 25] = 0
price

array([[170, 177, 169],
       [150, 159, 153],
       [  0,  27,  26],
       [165, 170, 167],
       [  0,   0,   0],
       [155, 116, 157]])

花式索引
- 花式索引是获取数组中想要的特定元素的有效方法

In [32]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
# 假设你想按特定顺序来获取第 5, 4 和 7 行时，用 arr[ [4,3,6] ]
arr[[4,3,6]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [24, 25, 26, 27]])

In [36]:
# 假设你想按特定顺序来获取倒数第 4, 3 和 6 行时 (即正数第 4, 5 和 2 行)，用 arr[ [-4,-3,-6] ]
arr[[-4,-3,-6]]

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 8,  9, 10, 11]])