In [1]:
import numpy as np

数组的变形  
- 重塑(reshape)和打平(ravel,flatten)
- 合并(concatenate,stack)和分裂(split)
- 重复(repeat)和拼接(title)
- 其他操作(sort,insert,delete,copy)

重塑和打平
- 重塑(reshape)和打平(ravel,flatten)这两个操作仅仅只改变数组的维度
- 重塑是从低维到高维
- 打平是从高维到低维

In [4]:
# 将一维数组重塑成二维数组
arr = np.arange(12)
print(arr)
print(arr.reshape((3,4)))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


当你重塑高维矩阵时，不想花时间算某一维度的元素个数时，可以用「-1」取代，程序会自动帮你计算出来。比如把 12 个元素重塑成 (2, 6)，你可以写成 (2,-1) 或者 (-1, 6)。

In [5]:
print(arr.reshape((-1,4)))
print(arr.reshape((3,-1)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
# 将二维数组打平为一维数组
arr = np.arange(12).reshape((3,4),order='F')
print(arr)
ravel_arr = arr.ravel()
print(ravel_arr)
flatten_arr = arr.flatten()
print(flatten_arr)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[ 0  3  6  9  1  4  7 10  2  5  8 11]
[ 0  3  6  9  1  4  7 10  2  5  8 11]


ravel()或flatten()的不同之处是
- ravel()按行主序打平时没有复制原数组，按列主序打平时复制了原数组
- flatten()在打平时复制了原数组

In [13]:
# 代码验证 flatten
arr = np.arange(6).reshape((2,-1))
print(arr)
flatten = arr.flatten()
print(flatten)
flatten[0] = 10000
print(arr)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [14]:
# 代码验证 ravel在列主序的打平
arr = np.arange(6).reshape((2,-1))
ravel_F = arr.ravel(order='F')
ravel_F[0] = 100000
print(ravel_F)
print(arr)

[100000      3      1      4      2      5]
[[0 1 2]
 [3 4 5]]


In [15]:
# 代码验证 ravel在行主序的打平,没有复制原数组，原数组的第一个元素也改变了
arr = np.arange(6).reshape((2,-1))
ravel_C = arr.ravel(order='C')
ravel_C[0] = 100000
print(ravel_C)
print(arr)

[100000      1      2      3      4      5]
[[100000      1      2]
 [     3      4      5]]
