In [2]:
import numpy as np

数组 (array) 是相同类型的元素 (element) 的集合所组成数据结构 (data structure)  
注意一个关键字 axis，中文叫「轴」，一个数组是多少维度就有多少根轴。由于 Python 计数都是从 0 开始的.

数组创建的几种方法:  
1.按步就班的np.array()用于列表和元祖上  
2.定隔定点的np.arange()和np.linspace()  
3.一步登天的np.ones(),np.zeros()和np.randon.random()

In [6]:
# 按步就班法
# 注意，numpy 数组的输出都带有 array() 的字样，里面的元素用「中括号 []」框住。
# 函数 arange 的参数为起点 , 终点 , 间隔
l = [3.45,5,2,8,4.2]
np.array(l)

array([3.45, 5.  , 2.  , 8.  , 4.2 ])

定隔定点的np.arange()和np.linespace()
更常见的两种创建
- 定隔的arange:固定元素大小间隔
- 定点的linespace:固定元素个数

In [5]:
# arange
print(np.arange(8))
print(np.arange(2,8))
print(np.arange(2,8,2))

[0 1 2 3 4 5 6 7]
[2 3 4 5 6 7]
[2 4 6]


In [8]:
# linespace
print(np.linspace(2,6,3))
print(np.linspace(3,8,3))

[2. 4. 6.]
[3.  5.5 8. ]


In [ ]:
一步登天的np.ones(),np.zeros()和np.randon.random()  
用zeros()创建全是0的n维数组  
用ones()创建全是1的n维数组  
用random()创建随机n维数组  
用eye()创建对角矩阵(二维数组)

In [12]:
print(np.ones(5))
print(np.ones((2,3)))
print(np.random.random((2,3,4)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[0.09143043 0.88544459 0.35458896 0.6237767 ]
  [0.51059503 0.97675742 0.36627585 0.43190319]
  [0.71210618 0.41948408 0.78106816 0.02716702]]

 [[0.64778701 0.02828161 0.2221569  0.97296279]
  [0.10405113 0.59235863 0.08949057 0.01350451]
  [0.01205713 0.12044864 0.89955219 0.67997312]]]


In [15]:
# 对于函数 eye()，它的参数就是一个标量，控制矩阵的行数或列数：
# 默认设置 k = 0 代表 1 落在对角线上
# k = 1 代表 1 落在对角线右上方
# k = -1 代表 1 落在对角线左下方
print(np.eye(4,k=0))
print(np.eye(4,k=1))
print(np.eye(4,k=-1))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


数组的属性(attributes)和方法(methods)
type:数组类型
ndim:维度个数
len():数组长度为5，这只针对一维数组有意义
size:数组元素个数
shape:数组形状，即每个维度的元素个数，用元祖来表示，只有一维
stride:跨度，即在某一维度下为了获取到下一个元素需要跨过的字节数
float64:8个字节数(bytes)因此跨度为8
dtype：数组元素类型，是双精度浮点。

In [25]:
arr = np.array([3.5, 5, 2, 8, 4.2])
print('The type is ',type(arr))
print('The dimension is ',arr.ndim)
print('The length of array is ',len(arr))
print('The number of elements is ',arr.size)
print('The shape of array is ',arr.shape)
print('The stride of array is ',arr.strides)
print('The type of lelments is ',arr.dtype)

The type is  <class 'numpy.ndarray'>
The dimension is  1
The length of array is  5
The number of elements is  5
The shape of array is  (5,)
The stride of array is  (8,)
The type of lelments is  float64


In [ ]:
yi'weiyi'wei