In [1]:
import numpy as np

numpy是Python专门处理高维数组(high dimensional array)的计算的包

In [3]:
my_array = np.arange(100000)
my_list = list(range(100000))
# my_array,my_list

In [8]:
%time for _ in range(10): my_array2 = my_array *  2

Wall time: 974 µs


In [9]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 56.1 ms


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

数组维度的转换，把1，2，3维转置为2，1，3维

In [20]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])